hl.on("hyprland.start", function()
    hl.exec_cmd("dbus-update-activation-environment --systemd --all")
    hl.exec_cmd("qs -c noctalia-shell")
    hl.exec_cmd("dex --autostart ~/.config/autostart/pcloud.desktop")
    hl.exec_cmd("/usr/bin/swaybg -m fill -i ~/.local/share/wallpaper/wireframe-terrain-chrome.jpg")
    hl.exec_cmd("wl-paste --primary --watch wl-copy")
    hl.exec_cmd("clipse -listen")
    hl.exec_cmd("kitty")
    hl.exec_cmd("brave")
end)
