[manager]
show_hidden = false
sort_by="natural"
sort_reverse=false
linemode="mtime"
image_delay=5
image_quality=80
	
max_width=10
max_height=10

[preview]
wrap='yes'
image_delay=10
image_quality=70



[opener]
edit = [
	{ run = 'nvim "$@"', block = true },
]
play = [
	{ run = 'mpv "$@"', orphan = true, for = "unix" },
]
view = [
	{ run = 'kitty +kitten icat "$@"', block = true },
]
view2 = [
	{ run = 'gimp "$@"', block = true, orphan = true, for = "linux" },
]
open = [
	{ run = 'libreoffice "$@"', orphan = true, block = true, for = "linux" },
]
openpdf = [
	{ run = 'qpdfview "$@"', orphan = true, for = "linux" },
]
openvirt= [
	{ run = 'virt-viewer "$@"', orphan = true, for = "linux" },
]

[open]
prepend_rules = [
	{ name = "*.json", use = "edit" },
	{ name = "*.conf", use = "edit" },
	{ name = "*.yaml", use = "edit" },
	{ name = "README.md", use = "edit" },

	##handle pictures
	#{ name = "*.png", use = "view" },
	#{ name = "*.jpeg", use = "view" },
	#{ name = "*.jpg", use = "view" },

	#handle office extensions
	{ name = "*.xlsx", use = "open" },
	{ name = "*.xls", use = "open" },
	{ name = "*.csv", use = "open" },
	{ name = "*.pptx", use = "open" },
	{ name = "*.docx", use = "open" },
	{ name = "*.pdf", use = "open" },
	{ name = "*.odt", use = "open" },
	{ name = "*.dat", use = "edit" },

	{ name = "*.vv", use = "openvirt" },
	# Multiple openers for a single rule
	{ name = "*.html", use = [ "open", "edit" ] },
	{ name = "*.png", use = [ "view", "view2" ] },
	{ name = "*.jpeg", use = [ "view", "view2" ] },
	{ name = "*.jpg", use = [ "view", "view2" ] },
	{ name = "*.tiff", use = [ "view", "view2" ] },
]
append_rules = [
	{ name = "*", use = "my-fallback" },
]

[plugin]
prepend_preloaders = [
    # Office Documents
    { mime = "application/openxmlformats-officedocument.*", run = "office" },
    { mime = "application/oasis.opendocument.*", run = "office" },
    { mime = "application/ms-*", run = "office" },
    { mime = "application/msword", run = "office" },
    { name = "*.docx", run = "office" },
]

prepend_previewers = [
    # Office Documents
    { mime = "application/openxmlformats-officedocument.*", run = "office" },
    { mime = "application/oasis.opendocument.*", run = "office" },
    { mime = "application/ms-*", run = "office" },
    { mime = "application/msword", run = "office" },
    { mime = "application/pdf", run = "office"},
    { mime = "{audio,video}/*", run = "mediainfo"},
    { mime = "image/*", run = "magick"},
    # { mime = "application/subrip", run = "mediainfo"},
    { name = "*.docx", run = "office" },
    { name = "*.csv", run = "rich-preview"}, # for csv files
    { name = "*.md", run = "rich-preview" }, # for markdown (.md) files
    { name = "*.rst", run = "rich-preview"}, # for restructured text (.rst) files
    { name = "*.ipynb", run = "rich-preview"}, # for jupyter notebooks (.ipynb)
    { name = "*.json", run = "rich-preview"}, # for json (.json) files
#    { name = "*.lang_type", run = "rich-preview"} # for particular language files eg. .py, .go., .lua, etc.
]

[[plugin.prepend_fetchers]]
id   = "git"
name = "*"
run  = "git"

[[plugin.prepend_fetchers]]
id   = "git"
name = "*/"
run  = "git"
